-- Drop tables
drop table if exists capacitaciones CASCADE;
drop table if exists cursos CASCADE;
drop table if exists cursos_alumnos CASCADE;
drop table if exists notas CASCADE;
drop table if exists persona CASCADE;
drop table if exists titulos CASCADE;

-- Create them
create table capacitaciones (
    id bigint generated by default as identity,
    descripcion varchar(255),
    institucion varchar(255),
    title varchar(255),
    year integer not null,
    profesor_id bigint,
    primary key (id)
);

create table cursos (
    id integer generated by default as identity,
    cant_horas bigint not null,
    descripcion varchar(255),
    nombre varchar(255),
    nota_aprobacion double not null,
    dictado_por_id bigint,
    primary key (id)
);

create table cursos_alumnos (
    alumno_id bigint not null,
    curso_id integer not null,
    primary key (alumno_id, curso_id)
);

create table notas (
    id bigint generated by default as identity,
    nota double not null,
    alumno_id bigint,
    curso_id integer,
    primary key (id)
);

create table persona (
    dtype varchar(31) not null,
    id bigint generated by default as identity,
    apellido varchar(255),
    dni varchar(255),
    dni_tipo varchar(255),
    domicilio varchar(255),
    fecha_de_nacimiento date,
    nombre varchar(255),
    sexo varchar(255),
    telefono varchar(255),
    primary key (id)
);

create table titulos (
    id bigint generated by default as identity,
    institucion varchar(255),
    title varchar(255),
    year integer not null,
    profesor_id bigint,
    primary key (id)
);

//Relate tables
alter table persona add constraint persona_dni_constraint unique (dni);
alter table capacitaciones add constraint cap_profesor_id_constraint foreign key (profesor_id) references persona;
alter table titulos add constraint tit_profesor_id_constraint foreign key (profesor_id) references persona;
alter table cursos add constraint cursos_profesor_dicta_constraint foreign key (dictado_por_id) references persona;
alter table cursos_alumnos add constraint cursos_alumnos_curso_id_constraint foreign key (curso_id) references cursos;
alter table cursos_alumnos add constraint cursos_alumnos_alumno_id_constraint foreign key (alumno_id) references persona;
alter table notas add constraint nota_alumno_id_constraint foreign key (alumno_id) references persona;
alter table notas add constraint nota_curso_id_constraint foreign key (curso_id) references cursos;
